name: Vaildate Schema

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23-alpine 
      options: --user root 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run main.go
      run: |
        go run main.go
      env:
        GOOS: linux
        GOARCH: amd64
